spring:
  mail:
    host: localhost
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 1025
          auth: true
          starttls:
            enable: true
            required: true
